version: '3.1'
services:
  im_services:
    image: hub.chats-boss.com/im/im_services:jm_pro_1.0.16
    container_name: im_services
    restart: always
    ports:
      - "3033:3000"
    environment:
      - nacos_api_path=http://172.21.1.24:8848/nacos/v1/cs/configs
      - nacos_tenant=c0ca972b-c4ef-4dac-b37b-cde22b69d7c7
      - nacos_group=APP_H5_GROUP
      - nacos_dataId=APP-H5
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/logs/im_services:/im_services/logs
    command:
      node ./dist/server.js
