# docker stack deploy --compose-file website-cmd.yml im

version: '3.6'
networks:
  im_net:
    external: true

services:
  im-website:
    image: hub.chats-boss.com/im/im_jm_website:jm_pro_1.0.13
    restart: always
    hostname: im-website
    networks:
      - im_net
    healthcheck:
      disable: true
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.im == true]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - dubbo.registry.parameters.namespace=c0ca972b-c4ef-4dac-b37b-cde22b69d7c7
      - nacos_api_path=http://172.21.1.24:8848/nacos/v1/cs/configs
      - nacos_tenant=c0ca972b-c4ef-4dac-b37b-cde22b69d7c7
      - nacos_group=jetmessage_web_group
      - nacos_dataId=jetmessage_web
      #- SW_AGENT_NAME=im-web-smarttalk
      #- SW_AGENT_COLLECTOR_BACKEND_SERVICES=172.21.1.27:11800
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/im/logs/jm_website:/im_jm_website/logs
    command:
      node ./dist/server.js  
