---

- name: Set hostname
  hostname: name={{ inventory_hostname }}

- name: Replace a localhost entry with our own
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: 127.0.0.1 localhost

- name: "Comment IPv6 in /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: '(?i)^(::1.*)'
    line: '# \1'
    backrefs: yes
    state: present
    owner: root
    group: root
    mode: '0644'

- name: "Build hosts file (backups will be made)"
  lineinfile: >
    dest=/etc/hosts
    regexp='{{ hostvars[item].ansible_hostname }}$'
    line='{{ hostvars[item].ansible_default_ipv4.address }}       {{ item }} {{ hostvars[item].ansible_hostname }}'
    state=present
    backup=yes

  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items:
  - "{{ groups['all'] }}"

- name: "Get /etc/dhcp/dhclient.d/google_hostname.sh stat"
  stat: path=/etc/dhcp/dhclient.d/google_hostname.sh
  register: google_hostname

- name: "Comment /etc/dhcp/dhclient.d/google_hostname.sh if exist"
  lineinfile:
    dest: /etc/dhcp/dhclient.d/google_hostname.sh
    regexp: '^'
    line: '# '
#    backrefs: yes
    state: present
    owner: root
    group: root
    mode: '0644'
  when: google_hostname.stat.exists is defined and google_hostname.stat.exists == True
