---

- name: Get /etc/yum.repos.d/epel.repo
  stat: path=/etc/yum.repos.d/epel.repo
  register: epel_repo

- name: Install epel repo for Install k8s
  yum:
    name: 'epel-release.noarch'
    state: latest
  when: epel_repo.stat.exists is defined and epel_repo.stat.exists == False

- name: Install packages
  yum:
    name: ['conntrack', 'ipvsadm', 'ipset', 'jq', 'iptables', 'curl', 'sysstat', 'libseccomp', 'wget', 'nfs-utils']
    state: latest
