pkg_list:
  - bash-completion
  - bash-completion-extras
  - bind-utils
  - chrony
  - conntrack
  - curl
  - dstat
  - file
  - glances
  - htop
  - iftop
  - iproute
  - ipset
  - iptables
  - ipvsadm
  - jq
  - less
  - libseccomp
  - mlocate
  - mtr
  - net-tools
  - nload
  - nmap
  - nmap-ncat
  - procps
  - screen
  - sysstat
  - telnet
  - traceroute
  - tree
  - unzip
  - vim
  - wget
  - which
  - yum-utils
  - redis
