---
# 安装rsync服务
- name: "install rsync"
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - rsync

- name: "copy rsyncd.conf to dest_host"
  copy: src=rsyncd.conf dest=/etc/rsyncd.conf
  notify: restart rsyncd