---

# 声明判断条件
- name: "Condition: {{ flannel_pkg }}.tar.gz"
  stat: path="{{ local_temp_dir }}{{ flannel_pkg }}.tar.gz"
  register: flannel_tar_gz


- name: "Download {{ local_temp_dir }}{{ flannel_pkg }}.tar.gz"
  get_url:
    url: "{{ flannel_download_url }}"
    dest: "{{ local_temp_dir }}{{ flannel_pkg }}.tar.gz"
    validate_certs: False
  when: not flannel_tar_gz.stat.exists

- name: "Extract {{ local_temp_dir }}{{ flannel_pkg }}.tar.gz"
  unarchive:
    src: "{{ local_temp_dir }}{{ flannel_pkg }}.tar.gz"
    dest: "{{ local_temp_dir }}"
    copy: no

- name: "Copy <flanneld> to {{ local_setup_bin }}"
  copy:
    src: "{{ local_temp_dir }}{{ item }}"
    dest: "{{ local_setup_bin }}{{ item }}"
    mode: 0755
  with_items:
    - flanneld

