version: '3.6'
networks:
  im_f_net:
    external: true

services:
  im-admin2:
    image: hub.chats-boss.com/im/im_admin:jm_pro_1.0.3
    hostname: im-admin2
    networks:
      - im_f_net
    healthcheck:
      disable: true
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.im == h]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - nacos.config.server-addr=172.21.1.24:8848
      - nacos.config.namespace=cbe94cf9-5ba3-4857-8c3d-dbfa28d31239
      - SW_AGENT_NAME=im-admin
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=172.21.1.27:11800
      - JAVA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=10004 -Dcom.sun.management.jmxremote.rmi.port=10004 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=im-admin -javaagent:/agent/skywalking-agent.jar
    volumes:
      - /etc/localtime:/etc/localtime
     # - /var/h-im/logs/admin:/logs
