version: '3.6'

networks:
  im_net:
    external: true

services:
  core-h-ngx:
    image: hub.chats-boss.com/im/base/openresty:latest
    networks:
      im_net:
        aliases:
          - crm.h-im.com
          - smarttalk.h-im.com
          - api.h-im.com
          - file.h-im.com
          - ws.h-im.com
          - job.h-im.com
          - admin.h-im.com
          - robot.h-im.com
          - user.h-im.com
          - dl.h-im.com
    hostname: im_core-h-ngx
    healthcheck:
      disable: true
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.core-ngx == h]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - target: 28880
        published: 28880
        protocol: tcp
        mode: host
    environment:
      - nacos_server=http://172.21.1.24:8848/
      - nacos_group=api-gateway
      - nacos_tenant=cbe94cf9-5ba3-4857-8c3d-dbfa28d31239
      - nacos_dataid_redis=redis
      - nacos_dataid_public=public
      - nacos_dataid_limit=limit
      - nacos_dataid_rules=signature-limit
      - check_host=api-h.jet666.com
      - ip_white_list=172.21.0.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/h-im/conf/core-ngx/:/usr/local/openresty/nginx/conf/
      - /var/h-im/logs/core-ngx/:/usr/local/openresty/nginx/logs/
      - /var/h-im/lua/core-ngx/:/usr/local/openresty/nginx/lua/
      - /var/h-im/apps/static/:/usr/local/openresty/nginx/html/static/
      - /var/h-im/script/:/usr/local/openresty/nginx/script/
      - /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem:/usr/local/openresty/nginx/ssl/ca-bundle.crt
