version: '3.6'
networks:
  im_net:
    external: true

services:
  im-task:
    image: hub.chats-boss.com/im/im_task:jm_pro_1.0.1
    restart: always
    hostname: im-task
    networks:
      - im_net
    healthcheck:
      disable: true
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.im == true]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - dubbo.registry.parameters.namespace=c0ca972b-c4ef-4dac-b37b-cde22b69d7c7
      - nacos.config.server-addr=172.21.1.24:8848
      - nacos.config.namespace=c0ca972b-c4ef-4dac-b37b-cde22b69d7c7
      - spring.profiles.active=pro
      - SW_AGENT_NAME=im-task
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=172.21.1.27:11800 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/im/logs/task:/logs
