version: '3.3'
services:
  mongos2:
    image: mongo:4.0.2
    # mongo 3.6 版默认绑定IP为 127.0.0.1，此处绑定 0.0.0.0 是允许其他容器或主机可以访问
    command: mongos --configdb cfgrs/cfg1:27017,cfg2:27017,cfg3:27017 --bind_ip 0.0.0.0 --port 27017
    networks:
      - mongo
    # 映射宿主机的 27017 端口
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime
    depends_on:
      - cfg1
      - cfg2
      - cfg3
    deploy:
      restart_policy:
        condition: on-failure
      # 在集群内的每一台服务器上都启动一个容器
      # mode: global
      replicas: 1
      placement:
        constraints:
          - node.labels.mogo ==worker1

networks:
  mongo:
    external: true
