---

- hosts: new
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: true     # 收集客户端状态信息
  vars_files:
  -  vars/main.yml
  roles:
  - 00-system-info
  - 01-common
  - 11-certbot
  - lb-out
  - python3
  - 10-install-docker
  - dayud
    #- 50-install-k8s
