---

- hosts: lb-out-c
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: true     # 收集客户端状态信息
  vars_files:
  -  vars/main.yml
  roles:
  - 00-system-info
  - 01-common
  - 10-install-docker
    #- 50-install-k8s
