# This task disables swap for Kubernetes node (see https://github.com/kubernetes/kubernetes/pull/31996)
- name: Disable swap (1/2)
  shell: swapoff -a
  ignore_errors: true

- name: Remove swapfile from /etc/fstab (2/2)
  mount:
    name: swap
    fstype: swap
    state: absent
