version: '3.1'
networks:
  im_net:
    external: true

services:
  im-h-user:
    image: hub.chats-boss.com/im/im_user:jm_pro_1.7.0
    restart: always
    hostname: im-h-user
    networks:
      - im_net
    healthcheck:
      disable: true
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.im == h]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - dubbo.protocol.port=20880
      - nacos.config.server-addr=172.21.1.24:8848
      - nacos.config.namespace=cbe94cf9-5ba3-4857-8c3d-dbfa28d31239
      - dubbo.registry.parameters.namespace=c0ca972b-c4ef-4dac-b37b-cde22b69d7c7
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/h-im/logs/user:/logs
