# docker stack deploy --compose-file website-cmd.yml im

version: '3.6'
networks:
  im_net:
    external: true

services:
  im-h-website:
    image: hub.chats-boss.com/im/im_jm_website:jm_pro_1.0.12
    restart: always
    hostname: im-h-website
    networks:
      - im_net
    healthcheck:
      disable: true
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.im == h]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - nacos_api_path=http://172.21.1.24:8848/nacos/v1/cs/configs
      - nacos_tenant=cbe94cf9-5ba3-4857-8c3d-dbfa28d31239
      - nacos_group=jetmessage_web_group
      - nacos_dataId=jetmessage_web
      - dubbo.protocol.port=20880
      - dubbo.registry.parameters.namespace=c0ca972b-c4ef-4dac-b37b-cde22b69d7c7
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/h-im/logs/jm_website:/im_jm_website/logs
    command:
      node ./dist/server.js  
