version: '3.6'
networks:
  im_net:
    external: true

services:
  im-sm_website:
    image: hub.chats-boss.com/im/im_sm_website:jm_pro_1.0.4
    restart: always
    hostname: im-sm_website
    networks:
      - im_net
    healthcheck:
      disable: true
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.im == true]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - dubbo.registry.parameters.namespace=c0ca972b-c4ef-4dac-b37b-cde22b69d7c7
      - "nacos_api_path=http://172.21.1.24:8848/nacos/v1/cs/configs"
      - "nacos_tenant=c0ca972b-c4ef-4dac-b37b-cde22b69d7c7"
      - nacos_group=im_sm_website
      - nacos_dataId=im_sm_website
      - SW_AGENT_NAME=im-sm_website
      - SW_AGENT_COLLECTOR_BACKEND_SERVICES=172.21.1.27:11800
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/im/logs/sm_website:/logs
    command:
      node ./dist/server.js --
