---

- hosts: im-adm-005
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: true     # 收集客户端状态信息
  vars_files:
  -  vars/main.yml
  roles:
  - 00-system-info
  - 01-common
  - im-out
  - 10-install-docker
