pkg_list:
  - bash-completion
  - bash-completion-extras
  - chrony
  - cronie
  - supervisor
  - crontabs
  - dstat
  - python-pip
  - file
  - htop
  - iftop
  - rsync
  - iproute
  - jq
  - less
  - mlocate
  - net-tools
  - nload
  - nmap
  - nmap-ncat
  - procps
  - screen
  - sysstat
  - telnet
  - traceroute
  - tree
  - unzip
  - zlib-devel
  - vim
  - which
  - openssl
  - openssl-devel
  - bzip2-devel
  - ncurses-devel
  - sqlite-devel
  - readline-devel
  - tk-devel
  - gdbm-devel
  - db4-devel
  - libpcap-devel
  - xz-devel
  - libselinux-python
  - lrzsz
  - bind-utils
