version: '3.6'
networks:
  im_net:
    external: true

services:
  im-h-admin:
    image: hub.chats-boss.com/im/im_admin:jm_pro_1.7.2
    hostname: im-h-admin
    networks:
      - im_net
    healthcheck:
      disable: true
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.im == h]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - nacos.config.server-addr=172.21.1.24:8848
      - nacos.config.namespace=cbe94cf9-5ba3-4857-8c3d-dbfa28d31239
      - dubbo.protocol.port=20880
      - dubbo.registry.parameters.namespace=c0ca972b-c4ef-4dac-b37b-cde22b69d7c7
      #- SW_AGENT_NAME=im-admin
      #- SW_AGENT_COLLECTOR_BACKEND_SERVICES=172.21.1.27:11800
      - JAVA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=10004 -Dcom.sun.management.jmxremote.rmi.port=10004 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=im-admin -javaagent:/agent/skywalking-agent.jar
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/h-im/logs/admin:/logs
