version: '3.6'
networks:
  im_net:
    external: true

services:
  im-h-chatbot:
    image: hub.chats-boss.com/im/im_chatbot:jm_pro_1.0.12
    restart: always
    hostname: im-h-chatbot
    networks:
      - im_net
    healthcheck:
      disable: true
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.chatbot == h]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - "NACOS_SERVER_ADDR=172.21.1.24:8848"
      - "NACOS_NAMESPACE=cbe94cf9-5ba3-4857-8c3d-dbfa28d31239"
      - dubbo.protocol.port=20880
      - dubbo.registry.parameters.namespace=c0ca972b-c4ef-4dac-b37b-cde22b69d7c7
      #- SW_AGENT_NAME=im-chatbot
      #- SW_AGENT_COLLECTOR_BACKEND_SERVICES=172.21.1.27:11800
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/h-im/logs/chatbot:/data/logs/nlp/chatbot
      - /var/h-im/data/model:/chatbot/model
