---
- name: "部署nginx应用前要创建相应的目录和拷贝nginx的配置文件"
  hosts: lg
  tasks:
    - name: "Mkdir directory"
      file: path={{ item }} state=directory
      with_items:
      - /var/lb/logs/rocketmq/node1-m
      - /var/lb/logs/rocketmq/node2-s
      - /var/lb/logs/rocketmq/node3-m
      - /var/lb/logs/rocketmq/node3-s
      - /var/lb/logs/rocketmq/node2-m
      - /var/lb/logs/zookeeper/zook-1
      - /var/lb/logs/zookeeper/zook-2
      - /var/lb/logs/zookeeper/zook-3
      - /var/lb/logs/zookeeper/zook-4
      - /var/lb/logs/zookeeper/zook-5
      - /var/lb/logs/zookeeper/zook-6
      - /var/lb/logs/fserver
      - /var/lb/logs/manager
      - /var/lb/logs/mdcenter
      - /var/lb/logs/rocketmq/node1-s
      - /var/lb/logs/fserver
      - /var/lb/logs/mdcenter
      - /var/lb/logs/manager
      - /var/lb/logs/api
      - /var/lb/logs/server
      - /var/lb/logs/hall
      - /var/lb/logs/schedule
      - /var/lb/logs/game-schedule
      - /var/lb/logs/cache-service
      - /var/lb/logs/line3/api
      - /var/lb/logs/line3/fserver
      - /var/lb/logs/line3/mdcenter
      - /var/lb/logs/line3/manager
      - /var/lb/logs/line3/server
      - /var/lb/logs/line3/hall
      - /var/lb/logs/line3/schedule
      - /var/lb/logs/line3/game-schedule
      - /var/lb/logs/line3/cache-service
      - /var/lb/logs/api-ngx
      - /var/lb/logs/hall-ngx
      - /var/lb/logs/manager-ngx
      - /var/lb/logs/mdcenter-ngx
      - /var/lb/logs/rcenter-ngx
      - /var/lb/logs/squid
      - /var/lb/data/rocketmq/node3-m
      - /var/lb/data/rocketmq/node1-s
      - /var/lb/data/rocketmq/node2-m
      - /var/lb/data/rocketmq/node2-s
      - /var/lb/data/rocketmq/node3-s
      - /var/lb/data/rocketmq/node1-m
      - /var/lb/data/zookeeper/zook-1
      - /var/lb/data/zookeeper/zook-2
      - /var/lb/data/zookeeper/zook-3
      - /var/lb/data/zookeeper/zook-4
      - /var/lb/data/zookeeper/zook-5
      - /var/lb/data/zookeeper/zook-6
      - /var/lb/apps/fserver
      - /var/lb/data/fserver/upload/tmp
      - /var/lb/data/fserver/upload/data
      - /var/lb/data/mq/mdcenter-rdb
      - /var/lb/data/mq/mdcenter-rdb
      - /var/lb/apps/mdcenter
      - /var/lb/data/mq/manager-rdb
      - /var/lb/apps/manager
      - /var/lb/apps/fserver
      - /var/lb/apps/manager
      - /var/lb/apps/api
      - /var/lb/apps/mdcenter
      - /var/lb/apps/server
      - /var/lb/apps/hall
      - /var/lb/apps/schedule
      - /var/lb/apps/cache-service
      - /var/lb/apps/game-schedule
      - /var/lb/apps/line3/mdcenter
      - /var/lb/apps/line3/fserver
      - /var/lb/apps/pay-impl-jars
      - /var/lb/apps/line3/manager
      - /var/lb/apps/line3/api
      - /var/lb/apps/line3/server
      - /var/lb/apps/line3/hall
      - /var/lb/apps/line3/schedule
      - /var/lb/apps/line3/cache-service
      - /var/lb/apps/line3/game-schedule
      - /var/lb/apps/pay-impl-jars
      - /var/lb/apps/pc-h5
      - /var/lb/apps/rcenter
      - /var/lb/apps/mobile-h5
      - /var/lb/data/mq/manager-rdb
      - /var/lb/data/mq/api-rdb
      - /var/lb/data/mq/server-rdb
      - /var/lb/data/mq/hall-rdb
      - /var/lb/data/mq/schedule-rdb
      - /var/lb/data/mq/game-schedule-rdb
      - /var/lb/data/mq/cache-service-rdb
      - /var/lb/data/line3/mq/mdcenter-rdb
      - /var/lb/data/line3/mq/manager-rdb
      - /var/lb/data/line3/mq/api-rdb
      - /var/lb/data/line3/mq/server-rdb
      - /var/lb/data/line3/mq/hall-rdb
      - /var/lb/data/line3/mq/schedule-rdb
      - /var/lb/data/line3/mq/game-schedule-rdb
      - /var/lb/data/line3/mq/cacheconf-service-rdb
      - /var/lb/
      - /var/lb/script
    - name: "Copy nginx's conf"
      copy: src=/var/env/lb/live/conf/ dest=/var/lb/conf/

