version: "3.3"

networks:
  lbnet:
    external: true

services:

  console:
    image: hub:5000/tomcat
    networks:
      - lbnet
    hostname: console
    environment:
        - JAVA_OPT=-Xms2500m -Xmx2500m -Xmn2g
    healthcheck:
      disable: true
    extra_hosts:
      - "pg-01.ld1:10.10.6.1"
      - "pg-02.ld2:10.10.6.2"
      - "pg-03.ld3:10.10.6.3"
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == lc]
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
    volumes:
      - /var/lb/apps/console:/usr/local/tomcat/webapps/
      - /var/lb/logs/console:/usr/local/tomcat/logs/
      - /var/lb/apps/console-static:/static
      - /var/lb/conf/console-ngx:/etc/nginx/
