version: "3.3"

networks:
  lbnet:
    external: true

services:

  fserver-1:
    image: hub:5000/tomcat-php
    networks:
      - lbnet
    hostname: fserver-1
    healthcheck:
      disable: true
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.fserver == 1]
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
    environment:
      - JAVA_OPT=-Xms4500m -Xmx4500m -Xmn4g
    volumes:
      - /var/lb/apps/fserver:/usr/local/tomcat/webapps/fserver/
      - /var/lb/logs/fserver:/usr/local/tomcat/logs/
      - /var/lb/data/fserver/upload/tmp:/data/upload/tmp/
      - /var/lb/data/fserver/upload/data:/data/upload/data/

  fserver-2:
    image: hub:5000/tomcat-php
    networks:
      - lbnet
    hostname: fserver-2
    healthcheck:
      disable: true
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.fserver == 2]
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
    environment:
      - JAVA_OPT=-Xms4500m -Xmx4500m -Xmn4g
    volumes:
      - /var/lb/apps/fserver:/usr/local/tomcat/webapps/fserver/
      - /var/lb/logs/fserver:/usr/local/tomcat/logs/
      - /var/lb/data/fserver/upload/tmp:/data/upload/tmp/
      - /var/lb/data/fserver/upload/data:/data/upload/data/
