version: "3.3"

networks:
  lbnet:
    external: true

services:
  server-4:
    image: hub.dayu-boss.com/core/tomcat-php
    networks:
      - lbnet
    hostname: server-4
    healthcheck:
      disable: true
    extra_hosts:
      - "pg-01.ld1:10.10.6.1"
      - "pg-01.ld3:10.10.6.3"
      - "pg-02.ld2:10.10.6.2"
      - "pg-03.ld3:10.10.6.3"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.line == 1]
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
    environment:
      - JAVA_OPT=-Xms4500m -Xmx4500m -Xmn4g
      - idc=A
    volumes:
      - /var/lb/glusterfs/apps/pay-impl-jars:/data/impl-jars/pay
      - /var/lb/apps/server:/usr/local/tomcat/webapps/server
      - /var/lb/logs/server4:/usr/local/tomcat/logs/
      - /var/lb/data/mq/server4-rdb:/var/data/mq/rdb

  server-5:
    image: hub.dayu-boss.com/core/tomcat-php
    networks:
      - lbnet
    hostname: server-5
    healthcheck:
      disable: true
    extra_hosts:
      - "pg-01.ld1:10.10.6.1"
      - "pg-01.ld3:10.10.6.3"
      - "pg-02.ld2:10.10.6.2"
      - "pg-03.ld3:10.10.6.3"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.line == 2]
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
    environment:
      - JAVA_OPT=-Xms4500m -Xmx4500m -Xmn4g
      - idc=A
    volumes:
      - /var/lb/glusterfs/apps/pay-impl-jars:/data/impl-jars/pay
      - /var/lb/apps/server:/usr/local/tomcat/webapps/server
      - /var/lb/logs/server5:/usr/local/tomcat/logs/
      - /var/lb/data/mq/server5-rdb:/var/data/mq/rdb

  server-6:
    image: hub.dayu-boss.com/core/tomcat-php
    networks:
      - lbnet
    hostname: server-6
    healthcheck:
      disable: true
    extra_hosts:
      - "pg-01.ld1:10.10.6.1"
      - "pg-01.ld3:10.10.6.3"
      - "pg-02.ld2:10.10.6.2"
      - "pg-03.ld3:10.10.6.3"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.line == 3]
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
    environment:
      - JAVA_OPT=-Xms4500m -Xmx4500m -Xmn4g
      - idc=A
    volumes:
      - /var/lb/glusterfs/apps/pay-impl-jars:/data/impl-jars/pay
      - /var/lb/apps/server:/usr/local/tomcat/webapps/server
      - /var/lb/logs/server6:/usr/local/tomcat/logs/
      - /var/lb/data/mq/server6-rdb:/var/data/mq/rdb
